# Global
maxplayers: 200
log_commands: true
motd: '&cProxy made by &bBluplayz! :)'

# Language
language:
  console: de_DE
  fallback: en_EN

# MySQL connection data
data:
  mysql:
    host: localhost
    port: 3306
    username: root
    database: bungeepe
    password: ''
  netty:
    port: 19132

# Server
server:
  options:
    priorities:
    - SilentLobby-1
    - Lobby-1
  Lobby-1:
    address: localhost:19133
    permission: ''
  SilentLobby-1:
    address: localhost:19140
    permission: 'bungeepe.silentlobby'